### ISSUE TITLE
recipe for target 'lod' failed make: *** [lod] Error 2

### ISSUE THREAD

**Issue by harryhcs** [Neutree/gprs_build#4]
I cloned the GPRS_C_SDK recusivly. Then download this docker image and ran as mentioned in docs. But I get this error:

hermanstander$ docker run -it --name gprs_builder -v ~/apps:/apps neucrack/gprs_build /bin/bash
root@5ec91bfd7412:/# cd apps/GPRS_C_SDK
root@5ec91bfd7412:/apps/GPRS_C_SDK# ./build.sh app

===================Start build=====================
-- Param   number : 1
-- Compile mode   : debug
-- Core    number : 2
-- Compile project: app
-- Project path   : 
  |
   --/apps/GPRS_C_SDK/app
---------------------------------------------------
-- System Version : LINUX
---------------------------------------------------

[MAKE]  init

[AR]   libinit_debug.a
 

[MAKE]  libs

[MAKE]  libs/gps

[MAKE]  libs/gps/minmea

[CPP]  %-27s <== %s\n minmea.asm minmea.S
mips-elf-gcc: src/minmea.S: No such file or directory
mips-elf-gcc: no input files
/apps/GPRS_C_SDK/platform/compilation/cust_rules.mk:997: recipe for target '/apps/GPRS_C_SDK/build/app/libs/gps/minmea/obj/debug/minmea.o' failed
make[6]: *** [/apps/GPRS_C_SDK/build/app/libs/gps/minmea/obj/debug/minmea.o] Error 1
/apps/GPRS_C_SDK/platform/compilation/cust_rules.mk:834: recipe for target '/apps/GPRS_C_SDK/build/app/libs/gps/minmea/lib/libminmea_debug.a' failed
make[5]: *** [/apps/GPRS_C_SDK/build/app/libs/gps/minmea/lib/libminmea_debug.a] Error 2
/apps/GPRS_C_SDK/platform/compilation/cust_rules.mk:1030: recipe for target 'dependencies' failed
make[4]: *** [dependencies] Error 2
/apps/GPRS_C_SDK/platform/compilation/cust_rules.mk:1030: recipe for target 'dependencies' failed
make[3]: *** [dependencies] Error 2
/apps/GPRS_C_SDK/platform/compilation/cust_rules.mk:1030: recipe for target 'dependencies' failed
make[2]: *** [dependencies] Error 2
/apps/GPRS_C_SDK/platform/compilation/cust_rules.mk:748: recipe for target '/apps/GPRS_C_SDK/build/app//app.srec' failed
make[1]: *** [/apps/GPRS_C_SDK/build/app//app.srec] Error 2
/apps/GPRS_C_SDK/platform/compilation/cust_rules.mk:395: recipe for target 'lod' failed
make: *** [lod] Error 2
====== Build Time: 0s complete at 2019-06-01 09:46:56 =======
!!!!!!!!!!!!!!!!!!!!
   BUILD FAILED
!!!!!!!!!!!!!!!!!!!!
=============================================================

**Comment by Neutree** [comment]
check if there have files in minmea folder?

**Comment by harryhcs** [comment]
I see, your right, there is nothing in src folder under minmea. I will download and try again

**Comment by harryhcs** [comment]
That worked build SUCCESS. But why does the git pull recusive not download all the repos correct?

**Comment by Neutree** [comment]
maybe it tried but download failed, download manually by command `git submodule update --init`

**Comment by harryhcs** [comment]
Thanks, this issue is resolved
