### ISSUE TITLE
No GPRS_C_SDK in docker container 

### ISSUE THREAD

**Issue by tawfiek** [Neutree/gprs_build#7]
I pulled and rant your docker container but I can not find `/projects/GPRS_C_SDK`  to build !!

**Comment by Neutree** [comment]
maybe you mount wrong path

**Comment by boonya** [comment]
If you cloned `GPRS_C_SDK` into `~/Documents/GPRS_C_SDK` you have to mount `~/Documents/` directory like so:

```bash
docker run -it --name gprs_builder -v ~/Documents:/projects neucrack/gprs_build /bin/bash
```

**Comment by boonya** [comment]
I think the issue can be closed
